name: Cargo Spellcheck
description: Github Action for cargo-spellcheck

author: Bernhard Schuster, Michael Käser

branding:
  color: green
  icon: type

runs:
  using: docker
  image: docker://mickare/cargo-spellcheck:${GITHUB_REF##*/}
