name: Build and release the Docker Image

on:
  push
  # release:
  #   types: [published]

jobs:
  build:
    name: Build Dockerfile
    runs-on: ubuntu-latest

    steps:
      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Get current date
        run: echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> ${GITHUB_ENV}

      - name: Checkout the repository
        uses: actions/checkout@v2.3.4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      ######################################
      # Login to GitHub Container registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.GCR_USERNAME }}
          password: ${{ secrets.GCR_TOKEN }}
          registry: ghcr.io

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ci/docker/Dockerfile
          build-args: |
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_REPO=https://github.com/${{ github.repository }}.git
            BUILD_REVISION=${{ github.sha }}
            BUILD_VERSION=${{ steps.get_version.outputs.version }}
          push: true
          tags: |
            ghcr.io/mickare/cargo-spellcheck:${{ steps.get_version.outputs.version }}
